import { Router, Request, Response } from 'express'
import { requireAuth } from '../../middleware/auth'

const router = Router()

// ============================================
// SDK GENERATOR
// Generates client SDKs from API specification
// ============================================

interface ApiEndpoint {
  method: string
  path: string
  description: string
  params?: { name: string; type: string; required: boolean; description: string }[]
  body?: Record<string, { type: string; description: string }>
  response?: Record<string, { type: string; description: string }>
}

// Get available SDK languages
router.get('/languages', async (_req: Request, res: Response) => {
  res.json({
    languages: [
      { id: 'javascript', name: 'JavaScript/TypeScript', icon: '🟨', version: '1.0.0' },
      { id: 'python', name: 'Python', icon: '🐍', version: '1.0.0' },
      { id: 'go', name: 'Go', icon: '🔵', version: '1.0.0' },
      { id: 'ruby', name: 'Ruby', icon: '💎', version: '1.0.0' },
      { id: 'php', name: 'PHP', icon: '🐘', version: '1.0.0' },
      { id: 'java', name: 'Java', icon: '☕', version: '1.0.0' },
      { id: 'csharp', name: 'C#', icon: '🟣', version: '1.0.0' },
    ],
  })
})

// Generate SDK for a language
router.post('/generate', requireAuth, async (req: Request, res: Response) => {
  const { language, baseUrl, endpoints } = req.body

  if (!language || !baseUrl) {
    return res.status(400).json({ error: 'language y baseUrl requeridos' })
  }

  const apiEndpoints: ApiEndpoint[] = endpoints || getDefaultEndpoints()

  let code: string
  let filename: string
  let mimeType: string

  switch (language) {
    case 'javascript':
      code = generateJavaScript(baseUrl, apiEndpoints)
      filename = 'daya-client.js'
      mimeType = 'text/javascript'
      break
    case 'python':
      code = generatePython(baseUrl, apiEndpoints)
      filename = 'daya_client.py'
      mimeType = 'text/x-python'
      break
    case 'go':
      code = generateGo(baseUrl, apiEndpoints)
      filename = 'daya.go'
      mimeType = 'text/x-go'
      break
    default:
      return res.status(400).json({ error: `Lenguaje '${language}' no soportado aún` })
  }

  res.setHeader('Content-Type', mimeType)
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
  res.send(code)
})

// Preview SDK code
router.post('/preview', requireAuth, async (req: Request, res: Response) => {
  const { language, baseUrl } = req.body

  const endpoints = getDefaultEndpoints()
  let code: string

  switch (language) {
    case 'javascript':
      code = generateJavaScript(baseUrl || 'https://api.daya.ai', endpoints)
      break
    case 'python':
      code = generatePython(baseUrl || 'https://api.daya.ai', endpoints)
      break
    default:
      code = '// Preview not available for this language'
  }

  res.json({ code, language })
})

function generateJavaScript(baseUrl: string, _endpoints: ApiEndpoint[]): string {
  return `/**
 * DAYA AI JavaScript SDK
 * Auto-generated by DAYA SDK Generator
 * 
 * Usage:
 *   import { DayaClient } from './daya-client.js';
 *   const daya = new DayaClient('your-api-token');
 *   const response = await daya.chat.send('Hello!');
 */

class DayaClient {
  constructor(apiToken, options = {}) {
    this.baseUrl = options.baseUrl || '${baseUrl}';
    this.apiToken = apiToken;
    this.headers = {
      'Authorization': \`Bearer \${apiToken}\`,
      'Content-Type': 'application/json',
    };
  }

  async request(method, path, data = null) {
    const options = {
      method,
      headers: this.headers,
    };
    if (data && method !== 'GET') {
      options.body = JSON.stringify(data);
    }
    const response = await fetch(\`\${this.baseUrl}\${path}\`, options);
    if (!response.ok) {
      throw new Error(\`API Error: \${response.status} \${response.statusText}\`);
    }
    return response.json();
  }

  get chat() {
    return {
      send: (message, options = {}) => 
        this.request('POST', '/api/chat', { message, ...options }),
      list: () => 
        this.request('GET', '/api/chat/conversations'),
    };
  }

  get memory() {
    return {
      get: () => this.request('GET', '/api/memory'),
      add: (content, category) => 
        this.request('POST', '/api/memory', { content, category }),
    };
  }

  get tools() {
    return {
      catalog: () => this.request('GET', '/api/tools/catalog'),
      execute: (name, input) => 
        this.request('POST', \`/api/tools/\${name}/execute\`, { input }),
    };
  }

  get documents() {
    return {
      list: () => this.request('GET', '/api/documents'),
      upload: (file) => {
        const formData = new FormData();
        formData.append('file', file);
        return fetch(\`\${this.baseUrl}/api/documents\`, {
          method: 'POST',
          headers: { 'Authorization': \`Bearer \${this.apiToken}\` },
          body: formData,
        }).then(r => r.json());
      },
    };
  }
}

module.exports = { DayaClient };
export default DayaClient;
`
}

function generatePython(baseUrl: string, _endpoints: ApiEndpoint[]): string {
  return `"""
DAYA AI Python SDK
Auto-generated by DAYA SDK Generator

Usage:
    from daya_client import DayaClient
    
    daya = DayaClient(api_token="your-api-token")
    response = daya.chat.send("Hello!")
"""

import requests
from typing import Optional, Dict, Any, List


class DayaClient:
    def __init__(self, api_token: str, base_url: str = "${baseUrl}"):
        self.base_url = base_url.rstrip("/")
        self.api_token = api_token
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {api_token}",
            "Content-Type": "application/json",
        })

    def _request(self, method: str, path: str, data: Optional[Dict] = None) -> Dict[str, Any]:
        url = f"{self.base_url}{path}"
        response = self.session.request(method, url, json=data)
        response.raise_for_status()
        return response.json()

    @property
    def chat(self):
        return ChatModule(self)

    @property
    def memory(self):
        return MemoryModule(self)

    @property
    def tools(self):
        return ToolsModule(self)

    @property
    def documents(self):
        return DocumentsModule(self)


class ChatModule:
    def __init__(self, client: DayaClient):
        self.client = client

    def send(self, message: str, **options) -> Dict[str, Any]:
        return self.client._request("POST", "/api/chat", {"message": message, **options})

    def list(self) -> List[Dict]:
        return self.client._request("GET", "/api/chat/conversations")


class MemoryModule:
    def __init__(self, client: DayaClient):
        self.client = client

    def get(self) -> List[Dict]:
        return self.client._request("GET", "/api/memory")

    def add(self, content: str, category: str = "general") -> Dict:
        return self.client._request("POST", "/api/memory", {"content": content, "category": category})


class ToolsModule:
    def __init__(self, client: DayaClient):
        self.client = client

    def catalog(self) -> List[Dict]:
        return self.client._request("GET", "/api/tools/catalog")

    def execute(self, name: str, input_data: Dict) -> Dict:
        return self.client._request("POST", f"/api/tools/{name}/execute", {"input": input_data})


class DocumentsModule:
    def __init__(self, client: DayaClient):
        self.client = client

    def list(self) -> List[Dict]:
        return self.client._request("GET", "/api/documents")

    def upload(self, file_path: str) -> Dict:
        with open(file_path, "rb") as f:
            files = {"file": f}
            headers = {"Authorization": f"Bearer {self.client.api_token}"}
            response = requests.post(f"{self.client.base_url}/api/documents", headers=headers, files=files)
            response.raise_for_status()
            return response.json()
`
}

function generateGo(baseUrl: string, _endpoints: ApiEndpoint[]): string {
  return `package daya

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

type Client struct {
	BaseURL    string
	APIToken   string
	HTTPClient *http.Client
}

func NewClient(apiToken string) *Client {
	return &Client{
		BaseURL:    "${baseUrl}",
		APIToken:   apiToken,
		HTTPClient: &http.Client{},
	}
}

func (c *Client) request(method, path string, body interface{}) ([]byte, error) {
	var reqBody io.Reader
	if body != nil {
		jsonBody, err := json.Marshal(body)
		if err != nil {
			return nil, err
		}
		reqBody = bytes.NewBuffer(jsonBody)
	}

	req, err := http.NewRequest(method, c.BaseURL+path, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Authorization", "Bearer "+c.APIToken)
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	return io.ReadAll(resp.Body)
}

// Chat methods
type ChatMessage struct {
	Message string \`json:"message"\`
}

func (c *Client) ChatSend(message string) (map[string]interface{}, error) {
	body, err := c.request("POST", "/api/chat", &ChatMessage{Message: message})
	if err != nil {
		return nil, err
	}
	var result map[string]interface{}
	err = json.Unmarshal(body, &result)
	return result, err
}

// Memory methods
func (c *Client) MemoryGet() ([]byte, error) {
	return c.request("GET", "/api/memory", nil)
}

type MemoryItem struct {
	Content  string \`json:"content"\`
	Category string \`json:"category"\`
}

func (c *Client) MemoryAdd(content, category string) ([]byte, error) {
	return c.request("POST", "/api/memory", &MemoryItem{Content: content, Category: category})
}

// Tools methods
func (c *Client) ToolsCatalog() ([]byte, error) {
	return c.request("GET", "/api/tools/catalog", nil)
}

func (c *Client) ToolsExecute(name string, input map[string]interface{}) ([]byte, error) {
	return c.request("POST", fmt.Sprintf("/api/tools/%s/execute", name), map[string]interface{}{"input": input})
}
`
}

function getDefaultEndpoints(): ApiEndpoint[] {
  return [
    { method: 'POST', path: '/api/chat', description: 'Send chat message' },
    { method: 'GET', path: '/api/chat/conversations', description: 'List conversations' },
    { method: 'GET', path: '/api/memory', description: 'Get memories' },
    { method: 'POST', path: '/api/memory', description: 'Add memory' },
    { method: 'GET', path: '/api/tools/catalog', description: 'Get tools catalog' },
    { method: 'GET', path: '/api/documents', description: 'List documents' },
  ]
}

export default router
